const mongoose = require('mongoose');

// Payment model - prepared for future M-Pesa (Safaricom Daraja) integration.
// Version 1 does NOT process real payments. Admin may create records
// for featured/premium upgrades that are marked MANUAL.
const paymentSchema = new mongoose.Schema(
  {
    user: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: true,
      index: true
    },
    amount: { type: Number, required: true, min: 0 },
    // Kenya phone used to pay (STK push = 2547XXXXXXXX format)
    phone: { type: String, trim: true },
    // Unique reference generated by our system, e.g. "CC-8F2A1B"
    reference: { type: String, trim: true, unique: true },
    // ID returned by the M-Pesa API once a payment is initiated
    transactionId: { type: String, trim: true },
    // Daraja STK receipt number once the payment succeeds
    mpesaReceipt: { type: String, trim: true },
    paymentType: {
      type: String,
      enum: ['featured', 'premium', 'sponsored', 'advertisement', 'manual'],
      default: 'manual'
    },
    status: {
      type: String,
      enum: ['PENDING', 'SUCCESS', 'FAILED', 'REFUNDED'],
      default: 'PENDING',
      index: true
    }
  },
  { timestamps: true }
);

paymentSchema.index({ status: 1, createdAt: -1 });

module.exports = mongoose.model('Payment', paymentSchema);